export const contentData = [
  {
    id: 1,
    username: "Aekknon",
    title: "What is Depression?",
    categories: "Depression",
    depression: "Minimal",
    date: "30 April 2021",
  },
  {
    id: 2,
    username: "Aekknon",
    title: "How to Fight Depression Naturally",
    categories: "Health",
    depression: "Moderately Severe",
    date: "30 April 2021",
  },
  {
    id: 3,
    username: "Aekknon",
    title: "What is Depression?",
    categories: "Depression",
    depression: "Minimal",
    date: "30 April 2021",
  },
  {
    id: 4,
    username: "Aekknon",
    title: "What is Depression?",
    categories: "Depression",
    depression: "Minimal",
    date: "30 April 2021",
  },
  {
    id: 5,
    username: "Aekknon",
    title: "What is Depression?",
    categories: "Depression",
    depression: "Minimal",
    date: "30 April 2021",
  },
  {
    id: 6,
    username: "Aekknon",
    title: "What is Depression?",
    categories: "Depression",
    depression: "Minimal",
    date: "30 April 2021",
  },
  {
    id: 7,
    username: "Aekknon",
    title: "What is Depression?",
    categories: "Depression",
    depression: "Minimal",
    date: "30 April 2021",
  },
  {
    id: 8,
    username: "Aekknon",
    title: "What is Depression?",
    categories: "Depression",
    depression: "Minimal",
    date: "30 April 2021",
  },
  {
    id: 9,
    username: "Aekknon",
    title: "What is Depression?",
    categories: "Depression",
    depression: "Minimal",
    date: "30 April 2021",
  },
  {
    id: 10,
    username: "Aekknon",
    title: "What is Depression?",
    categories: "Depression",
    depression: "Minimal",
    date: "30 April 2021",
  },
];

export const videoData = [
  {
    id: 1,
    title: "What is depression? - Helen M. Farrell",
    username: "Vorawut",
    link: "https://www.youtube.com/watch?v=z-IR48Mb3W0",
    date: "30 April 2021",
  },
  {
    id: 2,
    title: "What is depression like?",
    username: "Aekknon",
    link: "https://www.youtube.com/watch?v=5OiN1Zikz08",
    date: "30 April 2021",
  },
];

export const categoryData = [
  {
    id: 1,
    categories: "Depression",
    username: "Vorawut",
    role: "Admin",
    date: "30 April 2021",
  },
  {
    id: 2,
    categories: "Depression",
    username: "Vorawut",
    role: "Admin",
    date: "30 April 2021",
  },
];

export const userData = [
  {
    id: 1,
    name: "Vorawut Permsaengsuwan",
    role: "Admin",
    email: "vorawut.pun@mail.kmutt.ac.th",
  },
  {
    id: 2,
    name: "Wisa Moolhom",
    role: "User",
    email: "wisa.gubewgibi@mail.kmutt.ac.th",
  },
  {
    id: 3,
    name: "Aekknon Phomsiriudom",
    role: "Admin",
    email: "aekknon.phomsiriudom@mail.kmutt.ac.th",
  },
  {
    id: 4,
    name: "Wisa Moolhom",
    role: "User",
    email: "wisa.gubewgibi@mail.kmutt.ac.th",
  },
  {
    id: 5,
    name: "Wisa Moolhom",
    role: "User",
    email: "wisa.gubewgibi@mail.kmutt.ac.th",
  },
  {
    id: 6,
    name: "Aekknon Phomsiriudom",
    role: "Admin",
    email: "aekknon.phomsiriudom@mail.kmutt.ac.th",
  },
  {
    id: 7,
    name: "Vorawut Permsaengsuwan",
    role: "Admin",
    email: "vorawut.pun@mail.kmutt.ac.th",
  },
  {
    id: 8,
    name: "Aekknon Phomsiriudom",
    role: "Admin",
    email: "aekknon.phomsiriudom@mail.kmutt.ac.th",
  },
  {
    id: 9,
    name: "Vorawut Permsaengsuwan",
    role: "Admin",
    email: "vorawut.pun@mail.kmutt.ac.th",
  },
  {
    id: 10,
    name: "Aekknon Phomsiriudom",
    role: "Admin",
    email: "aekknon.phomsiriudom@mail.kmutt.ac.th",
  },
];

export const promotionData = [
  {
    id: 1,
    promotion: "สุขภาพดี ดีต่อใจ",
    hospital: "Bangkok Hospital",
    expireDate: "31 August 2021",
    admin: "Aekknon",
  },
  {
    id: 2,
    promotion: "สุขภาพดี ดีต่อใจ",
    hospital: "Bangkok Hospital",
    expireDate: "31 August 2021",
    admin: "Aekknon",
  },
  {
    id: 3,
    promotion: "สุขภาพดี ดีต่อใจ",
    hospital: "Bangkok Hospital",
    expireDate: "31 August 2021",
    admin: "Aekknon",
  },
  {
    id: 4,
    promotion: "สุขภาพดี ดีต่อใจ",
    hospital: "Bangkok Hospital",
    expireDate: "31 August 2021",
    admin: "Aekknon",
  },
  {
    id: 5,
    promotion: "สุขภาพดี ดีต่อใจ",
    hospital: "Bangkok Hospital",
    expireDate: "31 August 2021",
    admin: "Aekknon",
  },
  {
    id: 6,
    promotion: "สุขภาพดี ดีต่อใจ",
    hospital: "Bangkok Hospital",
    expireDate: "31 August 2021",
    admin: "Aekknon",
  },
  {
    id: 7,
    promotion: "สุขภาพดี ดีต่อใจ",
    hospital: "Bangkok Hospital",
    expireDate: "31 August 2021",
    admin: "Aekknon",
  },
  {
    id: 8,
    promotion: "สุขภาพดี ดีต่อใจ",
    hospital: "Bangkok Hospital",
    expireDate: "31 August 2021",
    admin: "Aekknon",
  },
  {
    id: 9,
    promotion: "สุขภาพดี ดีต่อใจ",
    hospital: "Bangkok Hospital",
    expireDate: "31 August 2021",
    admin: "Aekknon",
  },
  {
    id: 10,
    promotion: "สุขภาพดี ดีต่อใจ",
    hospital: "Bangkok Hospital",
    expireDate: "31 August 2021",
    admin: "Aekknon",
  },
];
